site_name: 匡院笔记分享
site_url: https://water-mi.github.io/kym-doc/

repo_name: KYM-DOC
repo_url: https://github.com/water-mi/kym-doc
edit_uri: edit/main/docs/

theme: 
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.path
    - navigation.indexes 
    - navigation.top
    - search.suggest
    - search.highlight
    - content.action.view
    - content.code.copy

  font:
    text: LXGW WenKai Screen GB Screen
    code: JetBrains Mono
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode 
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tilde

extra_javascript:
  - _assets/javascripts/katex.js
  - _assets/javascripts/pdf-viewer.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - _assets/css/customize.css

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors

nav:
  - 主页: 
    - index.md
    - pdf 与代码块样例: test.md
  - 多专业合上/通修:
    - all/index.md
    - 近代应用数学:
      - 课程介绍: all/modern_applied_math/about.md
  - 计算机科学与技术:
    - cs/index.md
    - 编译原理: 
      - 课程介绍: cs/compiler/about.md
      - cs/compiler/chapter1.md
      - cs/compiler/chapter3.md
      - cs/compiler/chapter4.md
      - cs/compiler/chapter9.md
    - 计算机网络（2024 秋）: 
      - 课程介绍: cs/computer_network(2024Fall)/about.md
      - cs/computer_network(2024Fall)/chapter1.md
      - cs/computer_network(2024Fall)/chapter2.md
      - cs/computer_network(2024Fall)/chapter3.md
      - cs/computer_network(2024Fall)/chapter4.md
      - cs/computer_network(2024Fall)/chapter5.md
      - cs/computer_network(2024Fall)/chapter6.md
      - cs/computer_network(2024Fall)/chapter7.md
    - 计算机网络（2025 秋）: 
      - cs/computer_network(2025Fall)/about.md
    - 密码学原理:
      - cs/crypto/about.md
  - 人工智能（脑科学与人工智能）:
    - ai/index.md
    - 计算方法:
      - 课程介绍: ai/numerical_method/about.md
      - ai/numerical_method/notes.md